
services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    environment:
      POSTGRES_DB: cybergaz
      POSTGRES_USER: gaz
      POSTGRES_PASSWORD: cybergaz
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    ports:
      - '6379:6379'

  server:
    build:
      dockerfile: Dockerfile
    container_name: server
    command: npx drizzle-kit generate && npx drizzle-kit migrate && npm run dev
    ports:
      - "3000:3000"
    environment:
      SERVER_PORT: 3000
      POSTGRES_HOST: localhost
      POSTGRES_USER: gaz
      POSTGRES_DB: cybergaz
      POSTGRES_PASSWORD: cybergaz
      POSTGRES_PORT: 5432
    depends_on:
      - pgdb
